# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: eric laurits
description: >- # this means to ignore newlines until "baseurl:"
  educator, writer, recovering photographer
baseurl: "/bay" # the subpath of the site
url: "https://ericlaurits.github.io" # the base hostname & protocol for the site
og_image: /assets/img/profile.png
google_analytics: "#"

header:
  pages:
    - name: Home
      slug: /
    - name: Work
    - name: Blog
    - name: Newsletter

footer:
  show_powered_by: true
  contact:
    - name: Email
      value: eric@ericlaurits.com
      link: mailto:eric@ericlaurits.com
  follow:
    - name: Twitter
      link: http://twitter.com/ericlaurits
      username: "@ericlaurits"
    - name: Instagram
      link: http://instagram.com/ericlaurits
    - name: linkedin
      link: http://linkedin.com/in/ericlaurits
    - name: RSS
      link: /feed.xml

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
